meta_product_name: 'Lite It'
meta_title: 'Lite It - Make shooting easy'
meta_description: 'App that will help you setup and keep track of your studio lights.'
meta_image: 'logo.png' # should exist in `app/assets/images/`
